apiVersion: v1
kind: Secret
metadata:
  name: {{ include "durandal.fullname" . }}-secret
  labels:
    {{- include "durandal.labels" . | nindent 4 }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauthSecret | b64enc | quote }}
  DURANDAL_API_TOKEN: {{ .Values.secrets.durandalApiToken | b64enc | quote }}
  {{- if .Values.cloudSQL.enabled }}
  CLOUD_SQL_PASSWORD: {{ default "" .Values.cloudSQL.password | b64enc | quote }}
  {{- end }}
